### PR TITLE
Remove the duplicate Formatter (fixes #17)

### LINKED ISSUE #17: metron-bro-plugin-kafka doesn't build with Zeek 4.0.0
# Summary of the issue
metron-bro-plugin-kafka doesn't build with zeek 4.00 RC2

## Expected behavior
zkg install metron-bro-plugin kafka should result in 0 error code.

## Steps to reproduce
zkg install metron-bro-plugin kafka 

*Where applicable, consider providing a patch that uses the [end to end testing environment](https://github.com/seisollc/zeek-kafka/blob/main/docker/run_end_to_end.sh).*

## Logs, errors, etc.
in ~/.zkg/testing/metron-bro-plugin-kafka/clones/metron-bro-plugin-kafka/zkg.test_command.stderr:

kafka.l2s-l2e-no-overlap ... failed
  % 'bro ../../../scripts/Apache/Kafka/ /home/nahum/.zkg/testing/metron-bro-plugin-kafka/clones/metron-bro-plugin-kafka/tests/.tmp/kafka.l2s-l2e-no-overlap/l2s-l2e-no-overlap.bro > output' failed unexpectedly (exit code 134)
  % cat .stderr
  error in /usr/local/zeek/share/zeek/base/bif/packet_analysis.bif.zeek, line 15: identifier not defined: PacketAnalyzer::Tag
  error in /usr/local/zeek/share/zeek/base/bif/packet_analysis.bif.zeek, line 15: identifier not defined: PacketAnalyzer::Tag
  internal error in /usr/local/zeek/share/zeek/base/bif/packet_analysis.bif.zeek, line 29: internal variable peer_description missing
  /home/nahum/zeek-3.0.12/build/src/bro: line 32: 69816 Aborted                 (core dumped) "${base}/${new}" "$@"

kafka.l2s-set-l2e-set ... failed
  % 'bro ../../../scripts/Apache/Kafka/ /home/nahum/.zkg/testing/metron-bro-plugin-kafka/clones/metron-bro-plugin-kafka/tests/.tmp/kafka.l2s-s
et-l2e-set/l2s-set-l2e-set.bro > output' failed unexpectedly (exit code 134)
  % cat .stderr
  error in /usr/local/zeek/share/zeek/base/bif/packet_analysis.bif.zeek, line 15: identifier not defined: PacketAnalyzer::Tag
  error in /usr/local/zeek/share/zeek/base/bif/packet_analysis.bif.zeek, line 15: identifier not defined: PacketAnalyzer::Tag
  internal error in /usr/local/zeek/share/zeek/base/bif/packet_analysis.bif.zeek, line 29: internal variable peer_description missing
  /home/nahum/zeek-3.0.12/build/src/bro: line 32: 69836 Aborted                 (core dumped) "${base}/${new}" "$@"
etc.

## Your environment
* Version of Zeek
* Version or commit hash of the zeek-kafka package
* Operating System and version
zeek 4.0 RC 2
metron-bro-plugin-kafka 
Ubuntu 20.04

### PR DESCRIPTION
**Pull request by JonZeolla**
# Summary of the contribution
This fixes the issue reported in #17; this is not a breaking change and continues to work in the currently supported version of Zeek.

## Testing
Run `make e2e`

## Checklist
- [X] Confirm that any associated issues are indicated in the pull request title
- [X] Rebase your PR against the latest commit within the target branch
- [X] Include steps to verify and test the intended change
- [N/A] Write or update unit tests and/or integration tests to verify your changes
- [N/A] Run shellcheck against any new or updated shell scripts, indicating the reasoning behind any disabled checks
- [X] Indicate whether or not this is a breaking change
- [X] Ensure that any new dependencies are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)

### CODE REVIEW

**Comment by JonZeolla** [comment]
Still working on an issue with the linter, which is unrelated to the actual problem this fixes.

**Review by ottobackwards — APPROVED** [review]
+1

**Comment by ottobackwards** [comment]
@JonZeolla are there really 13 commits for this?

**Comment by JonZeolla** [comment]
@ottobackwards lol I was troubleshooting a CI issue that I couldn't reproduce locally at first.

**Pull request merged**
